//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwilightSoul.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwilightSoul.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(document).ready(function () {
        ///    //MovePageTitle
        ///    if (typeof g_disableCheckoutInEditMode != &apos;undefined&apos; &amp;&amp; !g_disableCheckoutInEditMode) {
        ///        $(&apos;.MoveToTitleZone&apos;).appendTo(&apos;#bt-pagetitle&gt;.container&apos;);
        ///    }
        ///
        ///    if ($(&apos;body&apos;).hasClass(&apos;cmsSP&apos;)) {
        ///        var pageTitle = &apos;&lt;h1&gt;&apos; + $(&apos;#Logo &gt; .ms-core-pageTitle &gt; span&apos;).text() + &apos;&lt;/h1&gt;&apos;;
        ///        $(&apos;#PageTitleZone&apos;).html(pageTitle);
        ///    }
        ///});.
        /// </summary>
        internal static string TwilightSoulDocumentReady {
            get {
                return ResourceManager.GetString("TwilightSoulDocumentReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(document).ready(function(){if(typeof g_disableCheckoutInEditMode==&quot;undefined&quot;||g_disableCheckoutInEditMode||$(&quot;.MoveToTitleZone&quot;).appendTo(&quot;#bt-pagetitle&gt;.container&quot;),$(&quot;body&quot;).hasClass(&quot;cmsSP&quot;)){var n=&quot;&lt;h1&gt;&quot;+$(&quot;#Logo &gt; .ms-core-pageTitle &gt; span&quot;).text()+&quot;&lt;\/h1&gt;&quot;;$(&quot;#PageTitleZone&quot;).html(n)}});.
        /// </summary>
        internal static string TwilightSoulDocumentReady_min {
            get {
                return ResourceManager.GetString("TwilightSoulDocumentReady_min", resourceCulture);
            }
        }
    }
}
