name: Build and Deploy Umbraco to Azure Web Apps

on:
  pull_request:
    branches:
      - website
  push:
    branches:
      - website
  workflow_dispatch:
  
jobs:
  BuildAndDeployToProd:
    environment: prod
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - name: checkout
      uses: actions/checkout@main

      # Log into Azure
    - name: login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: setup DotNet
      uses: actions/setup-dotnet
      with:
        dotnet-version: '8.0.x'

    - name: dotnet build and publish
      run: |
        dotnet restore ./src
        dotnet build ./src --configuration Release 
        dotnet publish ./src -c Release -o '../tswDeploy' 

    - name: 'Deploy to Azure Web apps'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.AZURE_WEBAPP_NAME }}
        package: '../tswDeploy'

    - name: logout
      run: |
        az logout
