name: Azure Resources

on:
  pull_request:
    branches:
      - website
  push:
    branches:
      - website
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: ${{ vars.AZURE_WEBAPP_PACKAGE_PATH }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - name: checkout
      uses: actions/checkout@main

      # Log into Azure
    - name: login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: setup DotNet
      uses: actions/setup-dotnet@v3

    - name: dotnet build and publish
      working-directory: ./src
      run: |
        dotnet restore
        dotnet build --configuration Release 
        dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/tsw'

    - name: 'Deploy to Azure Web apps'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/tsw'

    - name: logout
      run: |
        az logout
